prometheus:
  server:
    retention: 1h

    global:
      evaluation_interval: 30s
      scrape_interval: 60s
      scrape_timeout: 10s

    resources:
      requests:
        cpu: 500m
        memory: 1Gi

  #   nodeSelector:
  #     kubernetes.io/os: ${operating_system}

  #   persistentVolume:
  #     accessModes:
  #       - ReadWriteOnce
  #     enabled: true
  #     mountPath: /data
  #     size: 20Gi
  #     storageClass: gp2

  # alertmanager:
  #   enabled: false
  #   nodeSelector:
  #     kubernetes.io/os: ${operating_system}

  # kube-state-metrics:
  #   enabled: true
  #   nodeSelector:
  #     kubernetes.io/os: ${operating_system}
  #   resources:
  #     limits:
  #       cpu: 200m
  #       memory: 512Mi
  #     requests:
  #       cpu: 200m
  #       memory: 512Mi

  # pushgateway:
  #   enabled: false
  #   nodeSelector:
  #     kubernetes.io/os: ${operating_system}

  # nodeExporter:
  #   nodeSelector:
  #     kubernetes.io/os: ${operating_system}

  #   resources:
  #     limits:
  #       cpu: 200m
  #       memory: 512Mi
  #     requests:
  #       cpu: 200m
  #       memory: 512Mi

  # alertmanagerFiles:
  #   alertmanager.yml:
  #     global: {}
  #     route: 
  #       group_by: ['alertname','labels']
  #       group_wait: 30s
  #       group_interval: 5m
  #       repeat_interval: 3h
  #       # receiver: slack-alerting

  #     inhibit_rules:
  #       - source_matchers: [alertname="OutsideBusinessHours",ip="172.17.8.197"]        
  #         target_matchers: [alert_outside_business_hours="false"]

  # ruleFiles: {}
    
  # serverFiles:
  #   alerting_rules.yml: {}
  #   alerts:
  #       groups:
  #           - name: slack-alerting
  #             rules:
  # ### OutsideBusinessHours ###
  #             - alert: OutsideBusinessHours
  #               expr: (day_of_week() == 6 or day_of_week() == 0) or (hour() <= 24 or hour() >= 00)
  #               for: 1m
  #               labels:
  #                 alert_outside_business_hours: "false"
  #               annotations:  
  #                 tittle: Outside Business Hours
  #                 description: "This alert fires during outside business hours. It should be blackholed by Alertmanager"

  #   recording_rules.yml: {}
  #   rules: {}
